# Generated by Django 4.2.7 on 2023-12-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
        ('usuarios', '0002_usuario_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='destinos_guardados',
            field=models.ManyToManyField(blank=True, related_name='usuarios_destinos_guardados', to='viajes.viaje'),
        ),
    ]
