# Generated by Django 4.2.7 on 2023-12-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_imagen_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(upload_to='usuarios', verbose_name='Imágenes'),
        ),
    ]
