# Generated by Django 4.2.7 on 2023-12-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='imagenes',
            field=models.ImageField(upload_to='viajes', verbose_name='Imágenes'),
        ),
    ]
