# Generated by Django 4.2.7 on 2023-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_categoria_noticia_categoria_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
