# Generated by Django 4.2.7 on 2023-12-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='descripcion_imagen',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción imagen'),
        ),
    ]
