# Generated by Django 4.2.7 on 2023-12-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0003_alter_viaje_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaje',
            name='resumen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
