# Generated by Django 4.2.7 on 2023-12-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viaje_autor_viaje_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='resumen',
            field=models.CharField(max_length=200, null=True, verbose_name='Resumen'),
        ),
    ]
