# Generated by Django 4.2.7 on 2023-12-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contacto',
        ),
    ]
